<div id="wordcloud1" class="wordcloud"> 
	<span data-weight="9"> MCX </span>
	<span data-weight="5"> Profit </span>
	<span data-weight="13"> Commodity </span>
	<span data-weight="14"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="21"> Minimum Loss </span>
	<span data-weight="10"> MCX </span>
	<span data-weight="5"> Profit </span>
	<span data-weight="22"> Commodity </span>
	<span data-weight="9"> Sure MCX Tips </span>
	<span data-weight="8"> Fast Service </span>
	<span data-weight="9"> Stock Market </span>
	<span data-weight="13"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="24"> Minimum Loss </span>
	<span data-weight="9"> Sure MCX Tips </span>
	<span data-weight="14"> Fast Service </span>
	<span data-weight="9"> Stock Market </span>
	<span data-weight="18"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="21"> Minimum Loss </span>
	<span data-weight="9"> MCX </span>
	<span data-weight="5"> Profit </span>
	<span data-weight="13"> Commodity </span>
	<span data-weight="9"> Sure MCX Tips </span>
	<span data-weight="14"> Fast Service </span>
	<span data-weight="9"> Stock Market </span>
	<span data-weight="13"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="24"> Minimum Loss </span>
	<span data-weight="9"> Sure MCX Tips </span>
		<span data-weight="12"> Trading </span>
	<span data-weight="21"> Minimum Loss </span>
	<span data-weight="10"> MCX </span>
	<span data-weight="5"> Profit </span>
	<span data-weight="22"> Commodity </span>
	<span data-weight="9"> Sure MCX Tips </span>
	<span data-weight="8"> Fast Service </span>
	<span data-weight="9"> Stock Market </span>
	<span data-weight="13"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="24"> Minimum Loss </span>
	<span data-weight="9"> Sure MCX Tips </span>
	<span data-weight="14"> Fast Service </span>
	<span data-weight="9"> Stock Market </span>
	<span data-weight="18"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="21"> Minimum Loss </span>
	<span data-weight="9"> MCX </span>
	<span data-weight="5"> Profit </span>
	<span data-weight="13"> Commodity </span>
	<span data-weight="9"> Sure MCX Tips </span>
	<span data-weight="14"> Fast Service </span>
	<span data-weight="9"> Stock Market </span>
	<span data-weight="13"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="24"> Minimum Loss </span>
	<span data-weight="9"> Sure MCX Tips </span>
		<span data-weight="14"> Fast Service </span>
	<span data-weight="9"> Stock Market </span>
	<span data-weight="18"> Trade </span>
	<span data-weight="12"> Trading </span>
	<span data-weight="21"> Minimum Loss </span>
	<span data-weight="9"> MCX </span>
	<span data-weight="5"> Profit </span>
	<span data-weight="13"> Commodity </span>
	<span data-weight="9"> Sure MCX Tips </span>
</div>